
DROP TABLE TB_ALUNO;

--ALUNO
CREATE TABLE TB_ALUNO(
       Id INT PRIMARY KEY,
       Email NVARCHAR2(120) NOT NULL UNIQUE,
       Nome VARCHAR2(60) NOT NULL,
       Nascimento TIMESTAMP NULL,
       Active INT NOT NULL
);

DROP INDEX IDX_ALUNO_EMAIL;

CREATE INDEX IDX_ALUNO_EMAIL ON TB_ALUNO(Email);

--CURSO
CREATE TABLE TB_CURSO(
       Id INT NOT NULL,
       Nome VARCHAR2(60) NOT NULL,
       CategoriaId INT NOT NULL,
       
       CONSTRAINT PK_CURSO PRIMARY KEY (Id),
       CONSTRAINT FK_CURSO_CATEGORIA FOREIGN KEY (CategoriaId) REFERENCES TB_CATEGORIA(Id)); --so pode ser criada, quando a TB_CATEGORIA existir.
);

--CONCLUSÃO/PROGRESSO
CREATE TABLE TB_PROGRESSO(
       AlunoId INT NOT NULL,
       CursoId VARCHAR2(30) NOT NULL,
       Progresso INT NOT NULL,
       UltimaAtualizacao TIMESTAMP NOT NULL,
       
       CONSTRAINT PK_PROGRESSO PRIMARY KEY (AlunoId, CursoId)
);

--CATEGORIA
CREATE TABLE TB_CATEGORIA(
       Id INT NOT NULL,
       Nome VARCHAR2(60) NOT NULL,
       
       CONSTRAINT PK_CATEGORIA PRIMARY KEY (Id)
);
 

SELECT * FROM TESTE17;

