
DROP TABLE TB_CURSO;


--CATEGORIA
CREATE TABLE TB_CATEGORIA(
       Id INT NOT NULL,
       Nome VARCHAR2(60) NOT NULL,
       
       CONSTRAINT PK_CATEGORIA PRIMARY KEY (Id)
);

--CURSO
CREATE TABLE TB_CURSO(
       Id INT NOT NULL,
       Nome VARCHAR2(60) NOT NULL,
       CategoriaId INT NOT NULL,
       
       CONSTRAINT PK_CURSO PRIMARY KEY (Id),
       CONSTRAINT FK_CURSO_CATEGORIA FOREIGN KEY (CategoriaId) REFERENCES TB_CATEGORIA(Id) --so pode ser criada, quando a TB_CATEGORIA existir.
);